import { FlashCardTopic } from "../topics-data"

export const amazonLpStories: FlashCardTopic = {
  slug: "amazon-lp-stories",
  title: "Amazon Leadership Principles — Behavioral Stories (STAR)",
  tags: ["Amazon", "Leadership Principles", "Behavioral", "STAR", "Interviews"],
  cards: [
    {
      id: "lp-govt-school-performance",
      title: "Performance issues for a government school (low-end devices)",
      bullets: [
        "**Amazon LPs** — Customer Obsession · Ownership · Dive Deep · Insist on the Highest Standards · Learn and Be Curious",
        "**Situation** — One of our schools reported that teachers were experiencing **severe lag** while marking attendance on our mobile app. What stood out: **thousands of schools** used the same feature, but **only this one school** reported the issue.",
        "**Situation** — Instead of assuming a generic performance bug, I **scheduled a call** to understand their environment. It was a **government-funded school** where teachers used **older, low-end Android devices** with limited RAM and CPU. We had mostly tested on mid-range and flagship devices — this exposed a **gap in our validation process**.",
        "**Task** — Although it wasn't assigned to me, I **took ownership** of finding the root cause and making sure these teachers could work smoothly. The goal wasn't just to fix a bug, but to make the product work for **every customer, regardless of device**.",
        "**Action** — I reproduced the issue by **testing on lower-spec devices** and **profiling** the app. It ran well on modern devices, but rendering and navigation were noticeably **slower on older hardware**.",
        "**Action** — I weighed two options. Optimizing the existing app meaningfully within the school's timeline was hard given its size and dependencies. Instead I proposed a **lightweight version** focused only on the daily attendance workflows teachers actually needed.",
        "**Action** — I hadn't done much React Native performance work, so I **learned** profiling, **rendering optimization**, **memoization**, reducing unnecessary **re-renders**, simplifying the UI hierarchy, and optimizing network requests. I then worked closely with **QA** to validate it thoroughly.",
        "**Action** — Rather than assume it was solved, I asked teachers to use it in their **real classroom** for **two weeks** and scheduled a follow-up feedback session.",
        "**Result** — Feedback was **overwhelmingly positive** — attendance marking was now **smooth on their existing devices**, letting teachers finish daily work without frustration.",
        "**Result** — It also made us realize our mobile testing strategy needed to include **low-end devices**, reinforcing designing software for **all customers**, not just modern hardware.",
        "**What I Learned** — Customer problems are often rooted in their **environment**, not the software. It strengthened my **React Native performance** skills and the habit of **validating under real-world conditions** rather than ideal dev environments.",
      ],
    },
    {
      id: "lp-delay-release-trust",
      title: "Delaying a release to protect customer trust",
      bullets: [
        "**Amazon LPs** — Have Backbone; Disagree and Commit · Earn Trust · Customer Obsession · Insist on the Highest Standards · Are Right, A Lot",
        "**Situation** — We were expanding into the **Australian market**, where schools had **compliance requirements** needing new attendance functionality. The timeline was **extremely tight** — Australian schools start their academic year in January and we wanted it ready before onboarding.",
        "**Situation** — I was leading a significant part of this. By the **last week of December** development was complete, but the feature hadn't finished **QA and regression testing**.",
        "**Task** — Pressure to release was high, but I believed shipping an **untested compliance feature** was a **significant risk**, especially for **new customers** seeing our product for the first time. My job was to **balance the deadline with a reliable experience**.",
        "**Action** — I reviewed the remaining QA and identified several **important scenarios still unvalidated**. Since attendance is **business-critical**, releasing without testing risked **production issues during onboarding**.",
        "**Action** — Instead of simply disagreeing, I requested a discussion with my **manager and engineering director**. I acknowledged the deadline's importance, then explained why a **short delay would actually reduce business risk**.",
        "**Action** — I presented three points: (1) attendance wouldn't be heavily used in the **first week**, giving a buffer; (2) QA still had **important validation** remaining; (3) a **buggy first impression** would damage **customer trust** far more than a few days' delay.",
        "**Action** — Rather than an indefinite delay, I recommended **finishing QA first**, then a **controlled rollout**. After discussing tradeoffs, both my manager and director **agreed with the approach**.",
        "**Result** — We completed QA, fixed the issues, and **gradually enabled** the feature. The rollout was **smooth with no major production issues**; product and support later confirmed schools used it **without critical bugs** during onboarding.",
        "**What I Learned** — Sometimes the **fastest decision isn't the best decision**. Respectfully **challenging a decision with data** builds credibility — voice concerns when customers may be impacted, then **commit** once the team aligns.",
      ],
    },
    {
      id: "lp-ai-timetable",
      title: "Automating timetable creation using AI",
      bullets: [
        "**Amazon LPs** — Invent and Simplify · Ownership · Deliver Results · Customer Obsession · Think Big",
        "**Situation** — At Toddle, creating a school's **timetable** is one of the most critical onboarding tasks. Schools shared timetables in many formats — **PDFs, Excel sheets, scanned images** — and with **no automated import**, support had to **manually recreate** them.",
        "**Situation** — This meant manually creating bell schedules, periods, teachers, classes, and routines — **five to six hours** per school. Complex ones were **escalated to engineering** to write backend scripts or DB queries. As we grew, I saw this was a **recurring operational bottleneck**, not an isolated issue.",
        "**Task** — Although it wasn't on our roadmap, I believed we could greatly improve onboarding by **automating the import**. I **took ownership** of exploring whether **AI** could interpret the formats and produce a **structured timetable** users could review before importing.",
        "**Action** — I first spoke with the **support team** to learn the most common formats and their frequent manual mistakes, and I collected **real customer timetable examples** so I could design around **actual data, not assumptions**.",
        "**Action** — I proposed an **AI-assisted import tool**: users upload any supported format → AI extracts **classes, periods, teachers, rooms, schedules** → the system generates a **structured preview** → users **review, correct, and import** instead of building everything manually.",
        "**Action** — After approval, I **built it independently** within available bandwidth, tested extensively on **historical files**, and validated the output in **demo schools** to ensure imported timetables behaved correctly.",
        "**Action** — I didn't just hand it over — I ran a **one-hour training** with support, demoed use cases, answered questions, and **documented** the workflow. Two weeks later I ran a **feedback session** on real onboarding.",
        "**Result** — A task that took **five to six hours** could now be done in **ten to fifteen minutes**. Support mainly **reviewed the AI output** and fixed small issues (spelling, ambiguous values), **accelerating onboarding** and freeing them to **help customers** instead of doing data entry.",
        "**What I Learned** — Some of the **highest-impact engineering** comes from improving **internal operational efficiency**, not just customer-facing features. Involving users early, **training after launch**, and collecting **structured feedback** let me solve their real problem, not just ship something technically interesting.",
      ],
    },
    {
      id: "lp-code-review-feedback",
      title: "Improving my code-review process after critical feedback",
      bullets: [
        "**Amazon LPs** — Learn and Be Curious · Earn Trust · Insist on the Highest Standards · Hire and Develop the Best",
        "**Situation** — As I grew on the team, I started reviewing **pull requests** from junior engineers. In a **1:1**, my manager gave **constructive feedback**: my reviews were technically correct, but I often reviewed PRs **between meetings, dev work, and Slack messages** — so some **edge cases** slipped through and were caught later in **QA**.",
        "**Situation** — Reflecting, I agreed. I wasn't treating reviews as **focused engineering work** — they'd become something I squeezed in between tasks.",
        "**Task** — I wanted to improve the **quality and consistency** of my reviews to give better guidance and **catch issues earlier** in the cycle.",
        "**Action** — Instead of just trying to 'be more careful,' I **changed my process**: I blocked a dedicated **90-minute focus window** for PR reviews — notifications off, no meetings, no switching back to my own code.",
        "**Action** — I reviewed more **systematically**: beyond 'does it work,' I focused on **edge cases, readability, maintainability, performance implications, and coding standards**. Teammates learned my review window and **planned submissions** around it, making the process **predictable**.",
        "**Result** — I became **more confident** in review quality, **fewer issues escaped to QA**, and junior engineers got **detailed, actionable feedback** instead of quick approvals.",
        "**What I Learned** — Receiving critical feedback isn't about **defending your current process** — it's a chance to **improve how you work**. That mindset stuck, and I keep looking for ways to refine my engineering practices.",
      ],
    },
    {
      id: "lp-decline-customer-request",
      title: "Declining a customer request after evaluating tradeoffs",
      bullets: [
        "**Amazon LPs** — Customer Obsession · Are Right, A Lot · Dive Deep · Earn Trust · Have Backbone; Disagree and Commit",
        "**Situation** — A newly onboarded school requested **real-time attendance synchronization** between mobile and web — mark attendance on mobile and it appears **instantly on the web portal without a refresh**. At first glance it sounded reasonable.",
        "**Task** — Instead of immediately accepting or rejecting, my job was to understand whether the problem **justified the engineering investment** and to find the **best solution for both the customer and the product**.",
        "**Action** — I ran a **discovery call** to understand their workflow and why real-time mattered, then discussed the **technical implications** with the engineering team.",
        "**Action** — True real-time sync would require **significant architectural changes** across frontend and backend — **persistent connections, event-driven synchronization, conflict handling, and infrastructure changes**. I also assessed **breadth of benefit**: it was unique to a **very small number of schools**, not a common product need.",
        "**Action** — Given the **high effort and limited impact**, I recommended **not prioritizing** it, and communicated the decision **transparently** — the technical tradeoffs, and why investing in **more broadly beneficial features** creates greater value for all customers.",
        "**Result** — The customer didn't get the exact feature they requested but **appreciated the transparency** and the rationale behind the decision.",
        "**What I Learned** — **Customer obsession doesn't always mean saying yes.** It means deeply understanding the problem, **carefully evaluating options**, and making decisions for the **greatest long-term value** — communicated **honestly**.",
      ],
    },
    {
      id: "lp-bulk-excuse-workflow",
      title: "Validating real customer workflows (bulk excuse creation)",
      bullets: [
        "**Amazon LPs** — Customer Obsession · Dive Deep · Ownership · Learn and Be Curious",
        "**Situation** — Early on the attendance team, I built a feature for admins to create **attendance excuses** for students. In requirements I noticed admins had to **search and add students one by one**. I asked our PM; the explanation was that excuses were usually for **individual students**, so a search-and-select flow was considered sufficient.",
        "**Situation** — I **accepted the assumption instead of validating it** with actual customer workflows — looking back, that was my mistake. I should have asked for **real usage examples** or spoken to **support** before finalizing the design.",
        "**Situation** — After release, we received **multiple support tickets**. A common case was **school trips or events** where an admin needed excuses for **over a hundred students at once**. With only individual selection, they had to **search and add every student manually** — what should have taken minutes became a frustrating chore.",
        "**Action** — Once I understood the real workflow, I **took ownership** and designed a richer **student selection interface**: **filter by grade, class, or year group**, **preview** the selected students, and **bulk-select** instead of searching one at a time.",
        "**Action** — I also spotted an unraised usability issue: selecting 120 students where one already had an excuse only showed a **generic conflict message** — it didn't say **which student**. Putting myself in the admin's shoes, they'd have to **inspect every selected student manually**.",
        "**Action** — Though not in the requirements, I redesigned it to **highlight the specific conflicting students** directly in the UI and let admins **remove them with a single click** before submitting.",
        "**Result** — Related **support tickets dropped significantly**, and support confirmed schools completed **bulk excuse creation much more efficiently**; resolving conflicts became far easier and the workflow more intuitive.",
        "**What I Learned** — Implementing the **documented requirement isn't enough** — validate whether the workflow **matches how customers actually use the product**. Since then I spend more time understanding **real customer scenarios** before locking in an implementation.",
      ],
    },
    {
      id: "lp-coaching-intern-ai",
      title: "Coaching an intern to use AI more effectively",
      bullets: [
        "**Amazon LPs** — Hire and Develop the Best · Earn Trust · Dive Deep · Insist on the Highest Standards",
        "**Situation** — I was the **onboarding buddy and code reviewer** for a software engineering intern, regularly reviewing his PRs. I noticed a **pattern**: implementations solved the **happy path** but repeatedly **missed edge cases**, didn't follow our **coding conventions**, and sometimes used patterns **inconsistent with our codebase**.",
        "**Situation** — At first I treated each PR independently with review comments, but after the **same issues recurred**, I realized the problem wasn't a specific feature — it was **how he approached development**.",
        "**Task** — Rather than leaving the **same comments on every PR**, I wanted to help him build **better engineering habits** so he could become **more independent** and submit **higher-quality code**.",
        "**Action** — Instead of assuming the cause, I scheduled a **1:1** to understand his workflow. I learned he **relied heavily on AI tools** to generate most implementations — fast, but often **submitted without fully understanding** the code or validating **edge cases**.",
        "**Action** — I made clear I wasn't **against AI** — I use it myself. I shared how I integrate it: to **brainstorm, clarify concepts, or draft**, but always **review, test, and adapt** before committing. I walked through examples from **his own PRs**, showing why some AI output didn't fit our **architecture** or missed **business scenarios**, and how to **think critically** about suggestions.",
        "**Result** — Over the following weeks his PRs improved in **quality and consistency** — he began **catching edge cases himself**, aligned with our **standards**, and needed **fewer repeated comments**.",
        "**What I Learned** — Mentoring works better when you address the **underlying behavior**, not just the symptoms. Coaching him to use **AI responsibly** — rather than discouraging it — made him a **stronger engineer** while preserving the **productivity benefits**.",
      ],
    },
  ],
}
